booking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('bookings/', views.BookingsView.as_view(), name="bookings"),
    path(
        'manage_bookings/',
        views.ManageBookingsView.as_view(),
        name='manage_bookings'
        ),
    path('edit/<booking_id>', views.edit_booking_date, name="edit"),
    path('edit_type/<booking_id>', views.edit_booking_type, name="edit_type"),
    path('cancel/<booking_id>', views.cancel_booking, name="cancel"),
    path(
        'past_bookings/',
        views.PastBookingsView.as_view(),
        name="past_bookings"
        ),
]

bookingpiano/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls'), name='booking_urls'),
    path('accounts/', include('allauth.urls')),
    path('', include(
        ('adminpanel.urls', 'admin_panel'),
        namespace='adminpanel')
        ),
    path('', include(
        ('adminpanel.urls', 'admin_past_bookings'),
        namespace='admin_past_bookings')
        ),
    path('', include(
        ('adminpanel.urls', 'admin_upcoming_bookings'),
        namespace='admin_upcoming_bookings')
        ),
    path('', include(
        ('home.urls', 'homepage'),
        namespace='homepage')
        ),
    path('', include(
        ('booking.urls', 'bookings'),
        namespace='bookings')
        ),
    path('', include(
        ('booking.urls', 'cancel_booking'),
        namespace='cancel_booking')
        ),
    path('', include(
        ('booking.urls', 'edit_booking_date'),
        namespace='edit_booking_date')
        ),
    path('', include(
        ('booking.urls', 'edit_booking_type'),
        namespace='edit_booking_type')
        ),
    path('', include(
        ('booking.urls', 'manage_bookings'),
        namespace='manage_bookings')
        ),
    path('', include(
        ('booking.urls', 'past_bookings'),
        namespace='past_bookings')
        ),
    path('', include(
        ('about.urls', 'about'),
        namespace='about')
        ),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.homepage, name="homepage"),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, date


class Bookings(models.Model):
    """
    Class for Bookings model
    """
    lesson = models.CharField(max_length=50)
    lesson_type = models.CharField(max_length=50)
    date = models.DateField()
    time = models.TimeField()
    status = models.BooleanField(default=False)
    student = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_lesson(self):
        """
        Return lesson name
        """
        return self.lesson

    def get_lesson_type(self):
        """
        Return lesson type name
        """
        return self.lesson_type

    def get_date(self):
        """
        Return date
        """
        return self.date

    def get_time(self):
        """
        Return time
        """
        return self.time

    def get_student(self):
        """
        Return student
        """
        return self.student

    def expired():
        """
        Set past dates to false
        """
        now = date.today()
        book = Bookings.objects.all()
        for b in book:
            if now > b.date:
                b.status = False
                b.save()

    class Meta:
        ordering = ['-date']
        verbose_name = 'Booking'
        verbose_name_plural = 'Bookings'

booking/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import generic
from .models import Bookings
from django.http import HttpResponseRedirect
from django.contrib import messages


class BookingsView(generic.ListView):
    """
    Render bookings page
    """
    model = Bookings
    template_name = "bookings.html"

    def get(self, request, *args, **kwargs):
        """
        Hide past dates
        """
        Bookings.expired()
        return super().get(request, *args, **kwargs)

    def post(self, request):
        """
        Create new booking
        """
        if request.method == 'POST':
            lesson = request.POST.get('lesson_inp')
            lesson_type = request.POST.get('lesson_type_inp')
            date = request.POST.get('date_inp')
            time = request.POST.get('time_inp')
            status = True
            student = request.user
            booking = Bookings(
                lesson=lesson,
                lesson_type=lesson_type,
                date=date,
                time=time,
                status=status,
                student=student)
            booking.save()
            messages.success(request, 'Booking successfully added.')
            return HttpResponseRedirect(reverse('manage_bookings'))


class ManageBookingsView(generic.ListView):
    """
    Render manage bookings page
    """
    model = Bookings
    template_name = "manage_bookings.html"

    def get(self, request, *args, **kwargs):
        """
        Hide past dates
        """
        Bookings.expired()
        return super().get(request, *args, **kwargs)


def edit_booking_date(request, booking_id):
    """
    Edit booking date and time
    """
    booking = get_object_or_404(Bookings, id=booking_id)
    if request.method == 'POST':
        booking.date = request.POST.get('edit_date_inp')
        booking.time = request.POST.get('edit_time_inp')
        booking.save()
        messages.success(request, 'Date successfully changed.')
        return redirect('manage_bookings')
    context = {
        'edit_date_lesson': Bookings.get_lesson(booking),
        'edit_date_lesson_type': Bookings.get_lesson_type(booking)
        }
    return render(request, 'edit_booking_date.html', context)


def edit_booking_type(request, booking_id):
    """
    Edit lesson type
    """
    booking = get_object_or_404(Bookings, id=booking_id)
    if request.method == 'POST':
        booking.lesson_type = request.POST.get('edit_lesson_type')
        booking.save()
        messages.success(request, 'Lesson type successfully changed.')
        return redirect('manage_bookings')
    context = {
        'edit_date_lesson_type': Bookings.get_lesson_type(booking)
        }
    return render(request, 'edit_booking_type.html', context)


def cancel_booking(request, booking_id):
    """
    Cancel booking
    """
    booking = get_object_or_404(Bookings, id=booking_id)
    if request.method == 'POST':
        booking.delete()
        messages.success(request, 'Lesson successfully canceled.')
        return redirect('manage_bookings')
    context = {
        'cancel_lesson': Bookings.get_lesson(booking),
        'cancel_lesson_type': Bookings.get_lesson_type(booking),
        'cancel_date': Bookings.get_date(booking),
        'cancel_time': Bookings.get_time(booking)
        }
    return render(request, 'cancel_booking.html', context)


class PastBookingsView(generic.ListView):
    """
    Render past bookings page
    """
    model = Bookings
    paginate_by = 19
    template_name = "past_bookings.html"

booking/templates/bookings.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Select and book a lesson  -->

    {% if user.is_authenticated %}

        <div class="container row mt-5" id="select-lesson">
            <div id="selection">
                <div>

                    <!-- Select piano or theory  -->
                    <div class="row d-flex justify-content-center" id="piano-theory">
                        <p class="h3 text-center">Select a lesson</p>
                        <div class="w-auto mt-3">
                            <button type="button" class="btn btn-outline-dark lesson-button" id="piano-btn">Piano</button>
                        </div>
                        <div class="w-auto mt-3">
                            <button type="button" class="btn btn-outline-dark lesson-button" id="theory-btn">Theory</button>
                        </div>
                    </div>

                    <!-- Select online or offline  -->
                    <div id="online-offline">
                        <p class="h3 text-center d-none" id="select-lesson-type">Select lesson type</p>
                        <div class="row justify-content-center" id="select-date-div">
                            <p class="h3 text-center d-none" id="select-date">Select date <a class="trigger"><i class="bi bi-info-circle-fill text-info trigger" id="info-icon"></i></a></p>
                            <div class="row d-flex justify-content-center d-none" id="book-for">
                                 Booking for&nbsp;
                                <span class="p-0 me-2 w-auto" id="piano-or-theory"></span>
                                <span class="p-0 w-auto" id="online-or-offline"></span>
                            </div>

                        </div>
                        <div class="row d-flex justify-content-center d-none" id="oo-buttons">
                            <div class="w-auto mt-3">
                                <button type="button" class="btn btn-outline-dark lesson-button" id="online-btn">Online</button>
                            </div>
                            <div class="w-auto mt-3">
                                <button type="button" class="btn btn-outline-dark lesson-button" id="offline-btn">Offline</button>
                            </div>

                            <!-- Back to lesson selection  -->
                            <div class="d-flex justify-content-center">
                                <button type="button" class="btn text-center mt-5 back-button" id="back-lesson"><i class="fa-solid fa-arrow-left fa-fw"></i>Back to lesson selection</button>
                            </div>
                        </div>
                    </div>

                    <!-- Select date  -->
                    <div id="calendar" class="d-none">
                        <div class="row d-flex justify-content-center">
                            <div class="col-3 mt-3 d-flex justify-content-center">
                                <div id="date" class="border border-dark">
                                    <div id="datepicker">
                                    </div>
                                    <input type="hidden" id="my_hidden_input">
                                </div>
                            </div>

                            <!-- Select time  -->
                            <fieldset class="d-flex justify-content-center mt-3 me-2 d-none" id="time-picker">
                                <label for="speed"></label>
                                <select name="speed" id="speed" class="border border-dark text-center">
                                    <option selected disabled hidden>Select time</option>
                                    <option>10:00 - 10:45</option>
                                    <option>11:00 - 11:45</option>
                                    <option>12:00 - 12:45</option>
                                    <option>13:00 - 13:45</option>
                                    <option>15:00 - 15:45</option>
                                    <option>16:00 - 16:45</option>
                                </select>
                            </fieldset>

                            <!-- Confirm booking button -->
                            <div class="mt-3 d-flex justify-content-center d-none" id="book-div">
                                <button type="button" class="btn text-center border border-dark" id="book-confirm">Book</button>
                            </div>

                            <!-- Back to lesson type selection  -->
                            <div class="d-flex justify-content-center">
                                <button type="button" class="btn text-center mt-5 back-button" id="back-lesson-type"><i class="fa-solid fa-arrow-left fa-fw"></i>Back to lesson type selection</button>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Book confirmation message -->
                <form method="POST">
                    {% csrf_token %}
                    <input type='hidden' name='lesson_inp' id='lesson_inp' value=''>
                    <input type='hidden' name='lesson_type_inp' id='lesson_type_inp' value=''>
                    <input type='hidden' name='date_inp' id='date_inp' value=''>
                    <input type='hidden' name='time_inp' id='time_inp' value=''>
                    <div class="row d-none border border-dark d-flex justify-content-around" id="confirm-message">
                        <div>
                            <p class="mt-3 h4 mb-0 text-center">This is booking for</p>
                        </div>
                        <div class="row d-flex justify-content-center confirmation-div">
                            <span class="h5 text-end p-0 me-2" id="lesson-confirmation"></span>
                            <span class="h5 text-start p-0" id="lesson-type-confirmation"></span>
                        </div>
                        <div class="row d-flex justify-content-center confirmation-div">
                            <span class="h5 text-end p-0 me-3" id="date-confirmation"></span>
                            <span class="h5 text-start p-0" id="time-confirmation"></span>
                        </div>
                        <div class="col-5 d-flex justify-content-center">
                            <button type="submit" class="btn text-center border border-dark bg-secondary bg-opacity-25" id="confirm"><i class="fa-solid fa-check fa-fw"></i>Confirm</button>
                        </div>
                        <div class="col-5 d-flex justify-content-center">
                            <button type="button" class="btn text-center border border-dark bg-secondary bg-opacity-25" id="back-to-selection">Back</button>
                        </div>
                    </div>
                </form>
            </div>

            <!-- My upcoming bookings  -->
            <div class="col-3" id="manage-bookings-side">
                <div class="text-center">
                    <p class="text-center h5 upc-lessons">
                        You currently don't have upcoming lessons.
                    </p>
                    <div class="mt-4">

                        {% for current in bookings_list %}
                            {% if current.student == request.user and current.status == True %}

                                <p id="upc-book">{{ current.lesson }} {{ current.lesson_type }} | {{ current.date }} - {{ current.time }}</p>
                            
                            {% endif %}
                        {% endfor %}

                    </div>
                    <div class="btn btn-outline-dark ms-auto" id="manage-bookings"><a class="text-reset text-decoration-none h6"  href="{% url 'manage_bookings:manage_bookings' %}">Manage bookings</a></div>
                </div>
            </div>
        </div>

        <!-- Pop-up on hover div -->
        <div id="pop-up">
            <p>
                Lessons can be booked up to 2 weeks in advance<br><br>
                Fully booked days, weekends and holidays are grayed-out
           </p>
         </div>

    <!-- Contacts  -->
    <div id="contacts">
        <p id="contacts-font">CONTACTS</p>
        <p>
            32 Nicholas Street <br>
            Cork <br>
            T12P9033 <br>
            Phone: +353 085 87654321 <br>
            E-mail: piano.email@school.com
        </p>
    </div>

    {% else %}

        <!-- Sign up or login message -->
        <p class="h3 mt-5 text-center">
            Please <a class="text-info text-decoration-none" href="{% url 'account_signup' %}"> Sign Up</a> 
            or <a class="text-info text-decoration-none" href="{% url 'account_login' %}">Login</a> in order to make a reservation
        </p>    

    {% endif %}

{%endblock%}

booking/templates/cancel_booking.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}

    <!-- Cancel lesson confirmation message -->
    <form method="POST">
        {% csrf_token %}
        <input type='hidden'>
        <div class="container d-flex justify-content-center mt-5">
            <div id="cancel-lesson" class="row mt-5 border border-dark d-flex justify-content-center ms-5">
                <div>
                    <p id="cancel-lesson-msg" class="lh-base mt-2 h4 mb-0 text-center">Are you sure you want to cancel the lesson?<br><strong>{{ cancel_lesson }} {{ cancel_lesson_type }} | {{ cancel_date }} - {{ cancel_time }}</strong></p>
                </div>
                <div class="mt-3 col ms-5">
                    <button type="submit" class="btn text-center border border-dark bg-secondary bg-opacity-25" id="cancel-lesson-confirm"><i class="fa-solid fa-check fa-fw"></i>Confirm</button>
                </div>
                <div class="mt-3 col">
                    <div class="btn text-center border border-dark bg-secondary bg-opacity-25 d-flex align-items-center justify-content-center" id="cancel-lesson-back-to-selection"><a class="text-reset text-decoration-none" href="{% url 'manage_bookings:manage_bookings' %}">Back</a></div>
                </div>
            </div>
        </div>
    </form>

    {% else %}

    <!-- Sign up or login message -->
    <p class="h3 mt-5 text-center">
        Please <a class="text-info text-decoration-none" href="{% url 'account_signup' %}"> Sign Up</a> 
        or <a class="text-info text-decoration-none" href="{% url 'account_login' %}">Login</a> to view your bookings
    </p>

    {% endif %}

{%endblock%}

booking/templates/edit_booking_date.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}

    <!-- Edit date and time -->
    <div class="mt-5 row row-cols-1 d-flex justify-content-center">
        <div class="text-center" id="edit-date-time">
            <p class="h3 mt-5 text-center">Edit date and time</p>
            <div class="mt-2">
                <div class="row d-flex justify-content-center" id="book-for">
                   <span class="p-0 me-2 w-auto" id="piano-or-theory">{{ edit_date_lesson }}</span>
                   <span class="p-0 w-auto" id="online-or-offline">{{ edit_date_lesson_type }}</span>
               </div>

                <!-- Select date  -->
                <div id="calendar">
                <div class="row d-flex justify-content-center">
                    <div class="col-3 mt-3 d-flex justify-content-center">
                        <div id="date" class="border border-dark">
                            <div id="datepicker">
                            </div>
                            <input type="hidden" id="my_hidden_input">
                        </div>
                    </div>

                    <!-- Select time  -->
                    <fieldset class="d-flex justify-content-center mt-3 me-2 d-none" id="time-picker">
                        <label for="speed"></label>
                        <select name="speed" id="speed" class="border border-dark text-center">
                            <option selected disabled hidden>Select time</option>
                            <option>10:00 - 10:45</option>
                            <option>11:00 - 11:45</option>
                            <option>12:00 - 12:45</option>
                            <option>13:00 - 13:45</option>
                            <option>15:00 - 15:45</option>
                            <option>16:00 - 16:45</option>
                        </select>
                    </fieldset>

                            <!-- Confirm booking button -->
                            <div class="mt-3 d-flex justify-content-center d-none" id="book-div">
                                <button type="button" class="btn text-center border border-dark" id="edit-book-confirm">Change</button>
                            </div>

                            <!-- Back to lesson type selection  -->
                            <div class="d-flex justify-content-center">
                                <div class="btn text-center mt-5 back-button" id="edit-back-lesson-type"><a class="text-reset text-decoration-none" href="{% url 'manage_bookings:manage_bookings' %}"><i class="fa-solid fa-arrow-left fa-fw"></i>Back to Manage booking</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Edit date confirmation message -->
            <form method="POST" class="d-flex justify-content-center">
                {% csrf_token %}
                <input type='hidden' name='edit_date_inp' id='edit_date_inp' value=''>
                <input type='hidden' name='edit_time_inp' id='edit_time_inp' value=''>
                <div id="edit-date-form" class="row mt-5 d-none border border-dark">
                    <div>
                        <p class="mt-3 h4 mb-0 text-center">Change date and time to:</p>
                    </div>
                    <div class="row d-flex justify-content-center confirmation-div">
                        <span class="h5 text-end p-0 me-3" id="edit-date-date"></span>
                        <span class="h5 text-start p-0" id="edit-time"></span>
                    </div>
                    <div class="mt-5 col ms-5">
                        <button type="submit" class="btn text-center border border-dark bg-secondary bg-opacity-25" id="edit-date-confirm"><i class="fa-solid fa-check fa-fw"></i>Confirm</button>
                    </div>
                    <div class="mt-5 col">
                        <div class="btn text-center border border-dark bg-secondary bg-opacity-25 d-flex align-items-center justify-content-center" id="edit-date-back-to-selection">Back</div>
                    </div>
                </div>
            </form>
        </div>

    {% else %}

    <!-- Sign up or login message -->
    <p class="h3 mt-5 text-center">
        Please <a class="text-info text-decoration-none" href="{% url 'account_signup' %}"> Sign Up</a> 
        or <a class="text-info text-decoration-none" href="{% url 'account_login' %}">Login</a> to view your bookings
    </p>

    {% endif %}

{%endblock%}

booking/templates/edit_booking_type.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}

    <!-- Edit lesson type confirmation message -->
    <form method="POST" class="d-flex justify-content-center mt-5">
        {% csrf_token %}
        <input type='hidden' name='edit_lesson_type' id='edit_lesson_type' value=''>
        <div id="edit-lesson-type" class="row mt-5 border border-dark d-flex justify-content-center">
            <div>
                <p id="edit_type_value" class="mt-4 h4 mb-0 text-center">Are you sure you want to change the lesson type to <strong>{% if edit_date_lesson_type == 'Online' %} Offline{% else %} Online{% endif %}</strong>?</p>
            </div>
            <div class="mt-5 col ms-5">
                <button type="submit" class="btn text-center border border-dark bg-secondary bg-opacity-25 p-2" id="edit-lesson-type-confirm"><i class="fa-solid fa-check fa-fw"></i>Confirm</button>
            </div>
            <div class="mt-5 col">
                <div class="btn text-center border border-dark bg-secondary bg-opacity-25 d-flex align-items-center justify-content-center" id="edit-lesson-type-back-to-selection"><a class="text-reset text-decoration-none" href="{% url 'manage_bookings:manage_bookings' %}">Back</a></div>
            </div>
        </div>
    </form>

{% else %}

<!-- Sign up or login message -->
<p class="h3 mt-5 text-center">
    Please <a class="text-info text-decoration-none" href="{% url 'account_signup' %}"> Sign Up</a> 
    or <a class="text-info text-decoration-none" href="{% url 'account_login' %}">Login</a> to view your bookings
</p>

{% endif %}

{%endblock%}

booking/templates/manage_bookings.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}

    <!-- My upcoming bookings -->
    <div class="mt-5 row row-cols-1 d-flex justify-content-center" id="manage-bookings-wrap">
        <div class="text-center">
            <p class="h3 mt-5 text-center upc-lessons">
                You currently don't have upcoming lessons.
            </p>
            <div class="mt-4">
                {% for current in bookings_list %}
                    {% if current.student == request.user and current.status == True %}

                    <div class="btn-toolbar d-flex justify-content-center mt-2 mb-2 h4">
                        <p class="btn-group me-3 mb-0 lh-lg" id="upc-manage-book">{{ current.lesson }} {{ current.lesson_type }} | {{ current.date }} - {{ current.time }}</p>
                        <div class="w-auto btn btn-outline-dark btn-group me-2 ps-2 pe-2 h-50 p-0 align-middle mt-1" id="change-date"><p class="m-0 p-0 h6 lh-lg"><a class="text-reset text-decoration-none" href="/edit/{{ current.id }}">Change date</a></p></div>
                        <div class="w-auto btn btn-outline-dark btn-group me-2 ps-2 pe-2 h-50 p-0 align-middle mt-1" id="change-type"><p class="m-0 p-0 h6 lh-lg"><a class="text-reset text-decoration-none" href="/edit_type/{{ current.id }}">Change type</a></p></div>
                        <div class="w-auto btn btn-outline-dark btn-group me-2 ps-2 pe-2 h-50 p-0 align-middle mt-1" id="cancel"><p class="m-0 p-0 h6 lh-lg"><a class="text-reset text-decoration-none" href="/cancel/{{ current.id }}">Cancel</a></p></div>
                    </div>

                    {% endif %}
                {% endfor %}
            </div>
            <div class="mt-3 btn btn-outline-dark" id="manage"><a class="text-reset text-decoration-none" href="{% url 'past_bookings:past_bookings' %}">View my past bookings</a></div>
        </div>
    </div>

    {% else %}

    <!-- Sign up or login message -->
    <p class="h3 mt-5 text-center">
        Please <a class="text-info text-decoration-none" href="{% url 'account_signup' %}"> Sign Up</a> 
        or <a class="text-info text-decoration-none" href="{% url 'account_login' %}">Login</a> to view your bookings
    </p>

    {% endif %}

{%endblock%}

booking/templates/past_bookings.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}

   <!-- My past bookings -->
   <div class="mt-5 row row-cols-1 d-flex justify-content-center">
        <div class="text-center">
            <p class="h3 mt-5 text-center">
                My completed lessons:
            </p>
        </div>
    </div>
    <div class="d-flex flex-wrap mt-4 row row-cols-3" id="cards-wrap">
        
            {% for past in bookings_list %}
                {% if past.student == request.user and past.status == False %}

                    <div class="card text-center m-2" id="cards">
                        <i class="fa-solid fa-check me-2 mt-2"></i><p class="card-body align-middle mb-0" id="past-book">{{ past.lesson }} <br> {{ past.lesson_type }} <br> <strong>{{ past.date }}</strong> <br> {{ past.time }}</p>
                    </div>

                {% endif %}
            {% endfor %}

    </div>
        <div class="pagination d-flex justify-content-center mt-5" id="pag">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a class="fw-bold text-dark text-decoration-none" href="?page=1">&laquo; first</a>
                    <a class="fw-bold text-dark text-decoration-none" href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
        
                {% if page_obj.paginator.num_pages > 1 %}
                <span class="current small">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% endif %}
        
                {% if page_obj.has_next %}
                    <a class="fw-bold text-dark text-decoration-none" href="?page={{ page_obj.next_page_number }}">next</a>
                    <a class="fw-bold text-dark text-decoration-none" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
            {% for past in bookings_list %}
                {% if past.student == request.user and past.status == False or past.status|length == 0 %}
                    <input type="hidden" value="{{ forloop.counter }}" class="count">
                {% endif %}
            {% endfor %}
        </div>

    <div class="d-flex justify-content-center mt-5 mb-5">
        <div class="btn text-center mt-5 back-button"><i class="fa-solid fa-arrow-left fa-fw"></i><a class="text-reset text-decoration-none h6 back-button"  href="{% url 'manage_bookings:manage_bookings' %}">Back to Manage Bookings</a></div>
    </div>

    {% else %}

    <!-- Sign up or login message -->
    <p class="h3 mt-5 text-center">
        Please <a class="text-info text-decoration-none" href="{% url 'account_signup' %}"> Sign Up</a> 
        or <a class="text-info text-decoration-none" href="{% url 'account_login' %}">Login</a> to view your bookings
    </p>

    {% endif %}

{%endblock%}