adminpanel/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path('admin_panel/', views.admin_panel, name="admin_panel"),
    path(
        'admin_past_bookings/',
        views.admin_past_bookings,
        name="admin_past_bookings"
        ),
    path(
        'admin_upcoming_bookings/',
        views.admin_upcoming_bookings,
        name="admin_upcoming_bookings")
]

bookingpiano/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls'), name='booking_urls'),
    path('accounts/', include('allauth.urls')),
    path('', include(
        ('adminpanel.urls', 'admin_panel'),
        namespace='adminpanel')
        ),
    path('', include(
        ('adminpanel.urls', 'admin_past_bookings'),
        namespace='admin_past_bookings')
        ),
    path('', include(
        ('adminpanel.urls', 'admin_upcoming_bookings'),
        namespace='admin_upcoming_bookings')
        ),
    path('', include(
        ('home.urls', 'homepage'),
        namespace='homepage')
        ),
    path('', include(
        ('booking.urls', 'bookings'),
        namespace='bookings')
        ),
    path('', include(
        ('booking.urls', 'cancel_booking'),
        namespace='cancel_booking')
        ),
    path('', include(
        ('booking.urls', 'edit_booking_date'),
        namespace='edit_booking_date')
        ),
    path('', include(
        ('booking.urls', 'edit_booking_type'),
        namespace='edit_booking_type')
        ),
    path('', include(
        ('booking.urls', 'manage_bookings'),
        namespace='manage_bookings')
        ),
    path('', include(
        ('booking.urls', 'past_bookings'),
        namespace='past_bookings')
        ),
    path('', include(
        ('about.urls', 'about'),
        namespace='about')
        ),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.homepage, name="homepage"),
]

adminpanel/views.py
from django.shortcuts import render
from booking.models import Bookings
from django.core.exceptions import PermissionDenied
from booking.filters import BookingFilter


def admin_panel(request):
    """
    Render admin panel
    """
    admin_piano = Bookings.objects.filter(lesson='Piano').count()
    admin_theory = Bookings.objects.filter(lesson='Theory').count()
    admin_online = Bookings.objects.filter(lesson_type='Online').count()
    admin_offline = Bookings.objects.filter(lesson_type='Offline').count()
    admin_completed = Bookings.objects.filter(status='False').count()
    admin_upcoming = Bookings.objects.filter(status='True').count()
    admin_total = Bookings.objects.all().count()
    context = {
        'admin_piano': admin_piano,
        'admin_theory': admin_theory,
        'admin_online': admin_online,
        'admin_offline': admin_offline,
        'admin_total': admin_total,
        'admin_completed': admin_completed,
        'admin_upcoming': admin_upcoming,
    }
    if not request.user.is_superuser:
        raise PermissionDenied

    return render(request, "admin_panel.html", context)


def admin_past_bookings(request):
    """
    Render admin past bookings
    """
    booking = Bookings.objects.filter(status=False)
    booking_filter = BookingFilter(request.GET, queryset=booking)
    context = {
        'booking_filter': booking_filter
    }
    if not request.user.is_superuser:
        raise PermissionDenied
    return render(request, "admin_past_bookings.html", context)


def admin_upcoming_bookings(request):
    """
    Render admin upcoming bookings
    """
    future_lessons = Bookings.objects.filter(status=True)
    future_filter = BookingFilter(request.GET, queryset=future_lessons)
    context = {
        'future_filter': future_filter
    }
    if not request.user.is_superuser:
        raise PermissionDenied
    return render(request, "admin_upcoming_bookings.html", context)

adminpanel/templates/admin_panel.html
{% extends "base.html" %}
{% load static %}

{% block content %}

   <!-- Admin panel -->
   <div class="container row mt-5 justify-content-between" id="admin-panel-parent">
        <div class="text-center"  id="admin-panel-div">
            <p class="h3 mt-5 text-center" id="admin-panel-p">
                Admin panel
            </p>
            <!-- Select completed on upcoming lessons  -->
            <div class="flex-column d-flex justify-content-center mt-4" id="admin-buttons-div">
                <div>
                    <div class="btn btn-outline-dark admin-buttons p-4" id="completed-lessons"><a class="text-reset text-decoration-none" href="{% url 'admin_past_bookings:admin_past_bookings' %}">Completed lessons</a></div>
                </div>
                <div class="mt-3">
                    <div class="btn btn-outline-dark admin-buttons p-4"><a class="text-reset text-decoration-none" href="{% url 'admin_upcoming_bookings:admin_upcoming_bookings' %}">Upcoming lessons</a></div>
                </div>
            </div>
        </div>

        <div class="w-auto position-absolute top-75 end-0 me-5" id="admin-stats-div">
            <div class="me-5">
                <p class="text-center h5 me-5">
                    Bookings stats:
                </p>
                <div class="mt-4 ps-4">
                    <p class="admin-stats">Piano:&nbsp;&nbsp;{{ admin_piano }}</p>
                    <p class="admin-stats">Theory:&nbsp;&nbsp;{{ admin_theory }}</p>
                    <p class="admin-stats">Online:&nbsp;&nbsp;{{ admin_online }}</p>
                    <p class="admin-stats">Offline:&nbsp;&nbsp;{{ admin_offline }}</p>
                    <p class="admin-stats">Completed:&nbsp;&nbsp;{{ admin_completed }}</p>
                    <p class="admin-stats">Upcoming:&nbsp;&nbsp;{{ admin_upcoming }}</p>
                    <p class="admin-stats mt-4">Total:&nbsp;&nbsp;{{ admin_total }}</p>
                </div>
            </div>
        </div>
    </div>

{%endblock%}

adminpanel/templates/admin_past_bookings.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Admin past bookings -->
    <div class="container-fluid row mt-5 justify-content-between">
        <div class="text-center">
            <p class="h3 mt-5 text-center" id="completed-lessons-p">
                Completed lessons
            </p>
        </div>
    </div>

    <div class="d-flex justify-content-center mt-4 text-center" id="admin-filter">
        <form method="GET" id="filter-form">
            {{ booking_filter.form.as_p }}
            <button type="submit" class="btn text-center border border-dark bg-light mt-3 mb-4 p-3 container-fluid">Search</button>
        </form>
    </div>

    <div class="mt-3 table-responsive" id="admin-table">
        <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Student</th>
                <th scope="col">Lesson</th>
                <th scope="col">Lesson type</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
            {% for past in booking_filter.qs %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td class="admin-results">{{ past.student }}</td>
                <td>{{ past.lesson }}</td>
                <td>{{ past.lesson_type }}</td>
                <td>{{ past.date }}</td>
                <td>{{ past.time }}</td>
                <td>Completed <i class="fa-solid fa-check me-2 mt-2"></i></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
    </div>

    <div class="text-center fw-bold d-none" id="no-records">
        No records found!
    </div>

    <div class="d-flex justify-content-center mt-5 mb-5">
        <div class="btn text-center mt-5 back-button"><i class="fa-solid fa-arrow-left fa-fw"></i><a class="text-reset text-decoration-none h6 back-button"  href="{% url 'adminpanel:admin_panel' %}">Back to Admin panel</a></div>
    </div>

{%endblock%}

adminpanel/templates/admin_upcoming_bookings.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Admin upcoming bookings -->
    <div class="container-fluid row mt-5 justify-content-between">
        <div class="text-center">
            <p class="h3 mt-5 text-center" id="completed-lessons-p">
                Upcoming lessons
            </p>
        </div>
    </div>

    <div class="mt-5 table-responsive" id="admin-upc">
        <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Student</th>
                <th scope="col">Lesson</th>
                <th scope="col">Lesson type</th>
                <th scope="col">Date</th>
                <th scope="col">Time</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
            {% for future in future_filter.qs %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td class="upc-results">{{ future.student }}</td>
                <td>{{ future.lesson }}</td>
                <td>{{ future.lesson_type }}</td>
                <td>{{ future.date }}</td>
                <td>{{ future.time }}</td>
                <td>Upcoming <i class="fa-solid fa-hourglass-start"></i></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
    </div>

    <div class="text-center fw-bold mt-4 d-none" id="upc-no-records">
        No upcoming lessons yet!
    </div>

    <div class="d-flex justify-content-center mt-5 mb-5">
        <div class="btn text-center mt-5 back-button"><i class="fa-solid fa-arrow-left fa-fw"></i><a class="text-reset text-decoration-none h6 back-button"  href="{% url 'adminpanel:admin_panel' %}">Back to Admin panel</a></div>
    </div>

{%endblock%}