about/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('about/', views.AboutView.as_view(), name="about")
]

bookingpiano/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls'), name='booking_urls'),
    path('accounts/', include('allauth.urls')),
    path('', include(
        ('adminpanel.urls', 'admin_panel'),
        namespace='adminpanel')
        ),
    path('', include(
        ('adminpanel.urls', 'admin_past_bookings'),
        namespace='admin_past_bookings')
        ),
    path('', include(
        ('adminpanel.urls', 'admin_upcoming_bookings'),
        namespace='admin_upcoming_bookings')
        ),
    path('', include(
        ('home.urls', 'homepage'),
        namespace='homepage')
        ),
    path('', include(
        ('booking.urls', 'bookings'),
        namespace='bookings')
        ),
    path('', include(
        ('booking.urls', 'cancel_booking'),
        namespace='cancel_booking')
        ),
    path('', include(
        ('booking.urls', 'edit_booking_date'),
        namespace='edit_booking_date')
        ),
    path('', include(
        ('booking.urls', 'edit_booking_type'),
        namespace='edit_booking_type')
        ),
    path('', include(
        ('booking.urls', 'manage_bookings'),
        namespace='manage_bookings')
        ),
    path('', include(
        ('booking.urls', 'past_bookings'),
        namespace='past_bookings')
        ),
    path('', include(
        ('about.urls', 'about'),
        namespace='about')
        ),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.homepage, name="homepage"),
]

about/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class About(models.Model):
    """
    Class for about model
    """
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=1000)
    image = CloudinaryField('image', default='placeholder', blank=True)

    class Meta:
        verbose_name = 'About'
        verbose_name_plural = 'Abouts'

    def __str__(self):
        """
        Return title
        """
        return self.title

about/views.py
from django.shortcuts import render
from django.views import generic
from .models import About


class AboutView(generic.ListView):
    """
    Render about page
    """
    model = About
    template_name = "about.html"

about/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        <div class="row mb-5">

            <!-- About entries -->
            
                {% for about in about_list %}
                    {% if forloop.counter|divisibleby:2 %}

                        <div class="row col-12 mt-5">
                            <div class="col-5 mt-5 img-div">
                                <img class="card-img-top" alt="about image" src=" {{ about.image.url }}">
                            </div>
                            <div class="col-6 mt-5 text-about">
                                <p class="h3 text-about">{{ about.title}}</p>
                                <p class="h5 text-about">{{ about.text}}</p>
                            </div>
                        </div>

                    {% else %}

                        <div class="row col-12 mt-5">
                            <div class="col-6 mt-5 text-about">
                                <p class="h3 text-about">{{ about.title}}</p>
                                <p class="h5 text-about">{{ about.text}}</p>
                            </div>
                            <div class="col-5 mt-5 img-div">
                                <img class="card-img-top w-75" alt="about image" src=" {{ about.image.url }}">
                            </div>
                        </div>

                    {% endif %}
                {% endfor %}
        </div>
    </div>

{%endblock%}